services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn auth_project.wsgi:application
    runtime: python3.8.12 # Ensure this matches your `runtime.txt`
