services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn attend_project.wsgi:application
    runtime: python3.11.3 # Ensure this matches your `runtime.txt`
#heeloo