# Generated by Django 5.0.6 on 2024-06-24 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attend_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_details',
            old_name='cont_nos',
            new_name='cont_no',
        ),
    ]
