# Generated by Django 5.0.6 on 2024-06-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend_app', '0002_rename_cont_nos_employee_details_cont_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='cont_no',
            field=models.IntegerField(),
        ),
    ]
