# Generated by Django 5.0.6 on 2024-06-24 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend_app', '0003_alter_employee_details_cont_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='cont_no',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
