# Generated by Django 5.0.6 on 2024-06-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend_app', '0004_alter_employee_details_cont_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='cont_no',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
